# Generated by Django 3.2.16 on 2022-11-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='myapp.student')),
            ],
        ),
    ]
