# Generated by Django 3.2.16 on 2022-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
