# Generated by Django 3.2.16 on 2022-11-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_photo_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
